#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX

tell application "Spotify"
  if it is running then
    if player state is playing then
      set track_name to name of current track
      set artist_name to artist of current track

      set cur_volume to get volume settings
      if artist_name > 0
        # If the track has an artist set and is therefore most likely a song rather than an advert
        if output muted of cur_volume is true then
          set volume without output muted
        end if
        "♫ " & artist_name & " - " & track_name
      else
        # If the track doesn't have an artist set and is therefore most likely an advert rather than a song
        if output muted of cur_volume is false then
          set volume with output muted
        end if
        "~ " & track_name
      end if
    end if
  end if
end tell
